
version: 2.1

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            pwd
            ls -la
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name my-stack
      # - run:
      #     command:  |
      #       aws cloudformation describe-stack-events --stack-name hakimm
workflows:
  my_workflow:
    jobs:
      - create_infrastructure